// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb3XLbuJJ+lS6eubD3kJLs2NkT3ewqlsbRjiOrbHl2pyJvCiZbEk5IgAFA2zq2n2ff",
	"Y59sCz/8kUjJUs5Maqo2uQlFAo1Go/vrH7SfvJAnKWfIlPS6T15KBElQoTC/zjhThDIUw2hM1EK/ilCG",
	"gqaKcuZ1vRtGv2YINEKm6IyigBkXoBYIYT7V8z18JEkao9f1kmXA5pQ9BtXPVFNKNX3fYyTR44rPn2nk",
	"+Z7ArxkVGHldJTL0PRkuMCGWX6VQaAL//YkE/+gE724P3ENw+9Tx3x695O8P/+0nz/fUMtULSCUom3sv",
	"Ly85tdUN17dafAKBkmciRBCYCpR662wOpNwyUCYVYSF6vpcKnqJQFA39UCBR+FlRvcv1FSY0QalIksLD",
	"AtmqFOGBSLCztUBmXCREeV0vIgoDQ05LiUSXLF7mUlrbqu/R6JtOsLqdV44yIY8XyOZaVd6+8b2Esvzn",
	"kb//Wb26obRRKa/y89GfKztbYb/gWrYbd/Lq2hLFPQ3NMZI4vpx53U9P3k8CZ17X+0u7tKq2U6/2tZ0w",
	"ZDPuvdyur6ApphhqctuIFFp4rQfrSYqoTO7ORUnATmzkJEujf0JNYyIVWBLfqqsvVZv/ZCVzW4zid3/H",
	"UHm+9xgQTIPcHit4IPWsyhE/VQHlRZNK40yQeEURPN+TlM2zmIjq+xI0vvxNljoSOAUIUsHvaYSiFYVJ",
	"i/J2OVFvo5D3WZqZU4oiqgVJ4nEFGawQ1gBnfFNCTciZVIJQDdProJKQx/opfSSPNMkSIHHMHzACTS3k",
	"AvX0hDL9zRil2xplCueaZfO1gZydAvOMCMIU7kFx7Sw1eQMU9QOtimvA7n8lYj+JDdg9FZwlyBTcE0HJ",
	"XYwQ4YwyQ6AmOOtsnnahYoY2oMA9ibNdadixr+m6W8kO3iqiYULmuKdOlZiuJ4M2LDqjIWmUj8AZCmQh",
	"NnlDjaMK4fJs6GgVo1tT9rOx+S58uhqcD68nV7+1b68G48vr4eTy6rdP3Unv/Pnf+8PzwfXkdspWcPlr",
	"RpbaipIlSdPu/VHr+FWJlWxuFdcFlaq+kTGZU6aRCmIqFfBZg9+rm1wFNLpPHlWYyJ2RWzPluCRCkKX+",
	"zfBRfU7JHD8r/gUb7G+iXxvXLFAJivc65NDQq2eCnqlZFyiz2CBEXWKbBfMREy6W+ymSnfM74lNiCT5Q",
	"tYCMUQUH2Jq3fJh6x+fvp55+ONEPh95qIKGjhb8efHz/fP7+efL+8KcmI90V0TbzcJTzcPxtPHwbBn5E",
	"RSKiyJYQJ3FDjGrkoc4Gc47JHcZy8zk/1SW3ZvSZVDyBL7gMDDxBSqiQNmAk87mJglkEMxorNBQaNteM",
	"ucV+9OfVkG3/kDJwT/+yNfK3rMiUNMHbL9kdCoYKJRSjdLgjsFB5CQ/6ZxmT7xfSGDlsPf0Rqgcuvuxn",
	"l26StscZnWeiWRNo2gCEPILhGEgUCZRyp+ibC5s0bvIxZgAoDviYcqm92n5IOeZC1dFyK5aZKd/oEjW7",
	"28KFMoZM3SrrEhQKWJbcWddBo9UsOLGI53Xfnp6+OX0tCrunkt7RmKplfaEP/AHUgkrLMZVOvpEWtQbi",
	"LEEhW1MWAOMMuzB2wxhXxVCeKcPhavieCh6ilHqq5kUwEndhUFLXoxdc+0kBYZxJhQKYVbkpgxwv+zz8",
	"ggKC1IeKIZ3Z8cMxuEzoUC+Dj/kyV0jChQmUZoInKwzqJdtuvco6lymy6wWdKbjimcKV1YZsrvW4fcFJ",
	"9J7E2o2LQxtrMC30T56Wjak+WAZMFOIeb6sRSWXAdpNe04+VM9xq6WMr9W/WWzv9FZsnYt5grD0xz3SU",
	"KvPTRabEMuWUqaq51mx/PYAJeZIQFjVFwjk94PcoBI1wL8LI7ncLr+Xe8OJSjP0AJvdUcv9kTvvGZI+4",
	"KbQZ40570dmljnSKUG6nWS7yqylymnkFra2ae+1KFptUcyW/sIEVZWmmYEYxjmzoYDzoWgWt7rHyXGen",
	"fdnMyMijjKB2lIibYILywgHvNDd32C+G+dyid/N0brydasoJnxfU1WR317LL1I6DnEiQHwAYahZZDeQT",
	"RWI+hwMShpgqjHzjHUioM6Es5eywKXgTVeXfaWOluZQls8+W7rrWOK8A+mu1HnmQZFLBHcK0RFgbg+dI",
	"XqrN7auVpCoLFf3wnYZV97hd84u623qMLISGJVuX00nZ5lqqY388GPWHo3PP965uRiP79HNveDHoe753",
	"M/pldPmfI8/3+oOLwWTQb9ij7w2E4A0166ufz+Ddyem/gj6imBKmAPVIjT8pZxLhYCz4XYwJ9FERGluL",
	"/DCZjKE3HsrD1pRNWV+HRBhppTJD9eqyO2XPMNFHdXM1hGeYUBUjPNu5VjjwPGXPQfHvee1/90vTabVa",
	"bUddtim7JzGNAuJcEzzD0L6CyquTTgfqcxlXwYxnLIJnGHEF+fNJ56RhNIl1jLsM8JFKJeEZevYFFC9O",
	"Ou8a5qUoEiol5SyIkFHUK4yLd1C8O+m8aZidMZKphVbv0NQdnuGm9uakcwRNkrGRiJGIe9RWgwKMAsAz",
	"nDaKJWPkntDYBFfPefgFq29PLbOVMKjPQ7lZp7qwVXU838tE7HW9hVKp7Lbb2syUIDoybFFUsxYX83bE",
	"w/ZCJXFbzEJN1AFgBfgjQ7whBs4SwgJ9XIZ/fExjwqybKTDPhDRUAg9DY5VhYwnPWETDRsf2bgc4i5eu",
	"1P3AdeCbcIEgSYKBgSqjmnZlS8qu15qyAQkXNqACS/oOJXC2MmVGaJwJbMEI9TlikqqlD0z/mDJJ2TzG",
	"wJBowYSnQYz3GIMVCuDXjMTSAMyMCqncWvoc7kj45YGIaMq06RPl4tCWOeCdwiSjUfZoXQ1laKcd14O0",
	"AtTq10tXw7Iw6K6WqCyPyMLRygEV9wWZoEFZ22tMQI1F1Ff9j+vLEYztV5gJMjegUfUpWovfvuscwf/+",
	"z9tDiHloQxAtSu0uUHscHi1tnAJqQRSEJDNZkObfsO2DTkNg6v2lrffTLjxHO0yzdkLZ1GtB784oUXFV",
	"YjccEqbd7R0CUUrQu0zZ/IqAPfImJrjIczhS0zl7roXk/i45C3LpNN1dbXBexnqd5wp5tHIalKk3x9U0",
	"9vTdu2oS2+k0pbFKu4UGX7/QKeli1YZlliRELJsYbo4YVpXLHe8yP0craefoc19boFGYBKng2q235lQt",
	"srsW5Zt9kOfvOrPwQLtPWXVDu8+ruaHdp675oN0nVpLh3ZfKvYwOXXa0bt97DPSZBfdEmAqcPrzh6Nfe",
	"xbDfuzq/+TgYTTzfG11Ofr68GelAqXdxNej1fxv81/B6cu353nhw9XF4fT28HPUHo6GLpXo3kw+D0WR4",
	"1puYN8PRZHA16l3Yj7/2hhe99xcD73Y9bHRaZLW5KS6somVNT4csovc0ykhcM1yTE1EGBJIsVjRYDc+8",
	"38Ebmgi0CrnrLPy/R9a9wHNNMdyBNKnEByRxU3uCfZ/DrOVKcVbUBGqH3tzlcEYYZzTUyR5RizzRqBAp",
	"K1gLy8kuTQ2bHEOV5wbae4B2Uepfy/NWqO52017sayOovLrhLG1ucrjGkLPIHE9oa5COiSK11sIQFjsL",
	"vt+81V5ww6LV4i4KadbZlAMXi9xlNI4gH18V0VGr0+rsfe3ggKw4SNd2VS7gBLJ3s4U7i2pnhX2Vt1UY",
	"JS8auMo+i+IQ92qycLP09qp9NdsucnLZWpNtKLfZ+vLnpssRV7sOigxs5aaknlK4DKqR1uCxRgMOdGRc",
	"LVUb6zjcdGtVJzoiCeYYUN/zP3GbU2ik+bxj7uAmNd/fbAKGav2nErEV1wba3fPIEvW9qrCayz41QK5y",
	"tXWfG1UkfX2qvf/xmqw+FVzxkDv3PSNZrCFrcqZ3tp562pFwMDkb+3DTHzeqgiJijmrDbdTEfKze7VjB",
	"vdKek4+qkK47txeT81l7MwuEquyn8fpnH2FsA8JaFcAFiCFPqnFje7vR12+i9RI1QNY2lBBGzEV02aEB",
	"lFVNwpm5bE3ZRAccvfEQZjyO+YOE3sCkPywiIi9OcyapVMjCJZBQcCmhsra0oUNMQ9TRWimCXkrCBcKx",
	"QehVCTw8PLSI+WwqIG6ubF8Mzwaj60Fw3Oq0FiqJK9lTFcXK2nquduN8/73xsALl2kMctTqaDE+RkZR6",
	"Xe9Nq9M6cbBvNLpNUtq+PyJxuiBH7dW2ljmqJvdt2k8QSL1hRtoKf2pbakwpJkudQmkzMu+Gkdf1LqhU",
	"Z9XGu2rf8adNvSLubtU2urhLeMVBoMoEAxNFuyAvtbVc01n8NUOTVLqjScij7bSR9B/GFRa9xIVNnna2",
	"5b1HHe3kt3e8NbfvUBbRSjhsAgj9w16P5X23W3ivdAhVGV/HPtPSaTMIc5DHnU5uqTqX7T55JE1jdyvT",
	"1vGuflfS26myb9qpDBKsoWEWhijlLIvjZd6shFFFSbRGnmzlyOWOf92PM1sDb+DoPYnyqN+uffT91u6V",
	"aTY1Mb5DWsPHm+/HR608rTk4/Z6nUFSspa1Yoxvoe3ndx8ICrOCCInMTXlZe3ppgpamX78z04gABhg/N",
	"Vy6rKGTHn1UvHbfBUHG7FsYUmcrv1jCCYb/eNd+C4cxU65x/ivwpy/MI1Hl/HMMcmeYHgTAY9s1ly5XV",
	"EHsnf5BqWB+Mg6Pj48PulAVwFLx9A+GCCBJqLiHmbK7fX2sssfBLIOYPKEIiEWLUETpwARGdU6VHuu3a",
	"svb6SOk7kJW+ua5eLNMFMtMPMmCRpV/StEPXGjg3/4nHGpiZv+woler3/dOBRkg0EPCeR8vfHw2txq/+",
	"ncpLDYaP/qiFN92/u+40kBVQ/oG/fxb8Pem8+34cnHE2i2moIIA+pjFfmsqdsWipk0fTeUlWLkD/lD7C",
	"gXwVtRudxIu/MbjNqwdbYtxMMHuxtlip1rkMWxZp9apDOUf1oay1/UER2Ie89FEPvVxGQCXkZblV2bky",
	"3tkCwy8VuTmK22W29ic0RmgxqoZEvm/e62A8Lznv4IvtpC2+uEkk5ZD2+p8qNgTBJ9s6lexmmpDyB1rl",
	"HJx8V7RyB8PyNo4/JRo5XX8VjfxXs+ktxgJ3Sxj2m9DmD7WXzveOVsps8YcV/rDCPazwHNUOAYHrQGxO",
	"7n7527baWlHFaxtDcfQ33JKF2r1CYauyTHly1+1v9kMxnWG4DGO0pUyTCDbSquzt5fbl/wIAAP//Xzu4",
	"wcg/AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
