// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbWXPjtrL+KyjcPNg31GLPkkQv98qSxsOKR1bJcs5JjX1cMNmSkCEBDgDKVhz991NY",
	"uEiktkkylYd5k0mg0Wh0f/11g37BAY8TzoApiTsvOCGCxKBAmL96nClCGQg/HBE1149CkIGgiaKc4Q6+",
	"ZfRzCoiGwBSdUhBoygVSc0BBNhV7GJ5JnESAOzheNtiMsudG+TXVkhIt38OMxHpc/vqBhtjDAj6nVECI",
	"O0qk4GEZzCEmVl+lQGgB//lIGr+3Gz/dn7gfjfuXtvf2bJU9P/2/77CH1TLRC0glKJvh1WqVSVvfcHWr",
	"+SskQPJUBIAEJAKk3jqbIVJsGVEmFWEBYA8ngicgFAUjPxBAFDwoqne5ucKExiAViRP0NAe2bkX0RCSy",
	"s7VBplzEROEODomChhGnrUTCaxYtMyttbNXDNPyiEyxvZ89RxuT5CthMu8rbVx6OKcv+PPOOP6u9G0pq",
	"nXKcnY9+XdrZmvq51rJVu5O9a0sQCxqYYyRRdD3FnY8v+DsBU9zB/9Mqoqrl3Kt1Yyf4bMrx6n5zBS0x",
	"gUCL2yUk98IbPVhPUkSl8nAtCgF2Yq0maRL+CTeNiFTIivhSX12VY/6jtcx9Poo//gaBwh5+bhBIGlk8",
	"lvBA6lmlI34pA8pKi0qiVJBozRGwhyVlszQiovy8AI1PP8rCRxrOARqJ4AsagmiGQdykvFVM1NvI7d1L",
	"UnNKYUi1IUk0KiGDNcIG4IxuC6gJOJNKEKphehNUYvJcPaUP5JnGaYxIFPEnCJGWFnABenpMmX5ngtJt",
	"jTIFM62yeVsjzk5Bs5QIwhQcIXHjLLV4AxTVAy2ba8AWvxBxnMUGbEEFZzEwhRZEUPIYAQphSpkRUDGc",
	"TTYvh0gxQ2tQYEGi9FAZduw+X3cr2cE7TeTHZAZH+lSB6Xoy0oFFpzQgtfYRMAUBLIC6bKhxVAG67vlO",
	"Vj66ecfemZjvoI/jwaV/Mxn/2rofD0bXN/7kevzrx86ke/nH//f9y8HN5P6OreHy55QsdRTFS5IkncVZ",
	"83yvxQo1d5rrikpV3ciIzCjTSIUiKhXi05q8Vw25Emh0XjBVEMuDkVsr5bQkQpCl/pvBs3pIyAweFP8E",
	"NfE30Y9NahagBIWFphwaevVMpGdq1QXINDIIUbXYdsN8gJiL5XGOZOf8hfgUW4FPVM1RyqhCJ9CcNT10",
	"h88vL+6w/vFa/zjF60RCs4XvTz5c/HF58cfk4vS7uiA9FNG263CW6XD+ZTp8GQZ+AEVCosgOihO7IcY1",
	"MqqzJZwj8giR3H7OL1XLbQR9KhWP0SdYNgw8oYRQIS1hJLOZYcEsRFMaKTASajZXj7n5fvTrdcp2PKVs",
	"uF//u5P5W1VkQurg7ef0EQQDBRLlozTdEZC7vERP+s+Ckx9HaYwddp7+ENQTF5+Oi0s3ScfjlM5SUe8J",
	"NKkBQh4if4RIGAqQ8iD2zYUtGrflGDMAKY7gOeFSZ7XjkHLEhaqi5U4sM1O+MCVqdXfRhYJDJm6VTQsK",
	"hVgaP9rUQcP1Kji2iIc7b9+8efVmHwtbUEkfaUTVsrrQe/6E1JxKqzGVzr6hNrUG4jQGIZt3rIEYZ9BB",
	"IzeMcZUP5akyGq7T90TwAKTUU7UugpGogwaFdD16znWeFCiIUqlAIGZd7o6hDC/7PPgEAjUSD5UCqWfH",
	"+yPkKqFTvQw8Z8uMgQRzQ5SmgsdrCuolW2690jrXCbCbOZ0qNOapgrXVfDbTfty64iS8IJFO4+LUcg2m",
	"jf4Ra9uY7oNVwLAQ9/O+zEhKA3aH9IZ/rJ3hzkgfWat/sd/a6XtinohZTbB2xSzVLFVmpwtMiWXCKVPl",
	"cK3E/iaBCXgcExbWMeFMHuILEIKGcJRgYIvD6LU8Gl5ciXEcwGSZSh5fzOncGB/BmwJbMR60F11daqaT",
	"U7mDZjnmV3HkJMW5rJ2ee+NaFttcc62+sMSKsiRVaEohCi11MBl0o4NWzVhZrXPQvmxlZOxRMKgDLeIm",
	"GFKeJ+CD5mYJe2WUzyL6sEznxtuppp3wMKeuJ3u4l10ndhzKhDSyA0BGmkVWA/lEkYjP0AkJAkgUhJ7J",
	"DiTQlVCacHZaR95E2fkP2lgRLkXL7MHK3fQalxWQflvuR57EqVToEdBdgbCWg2dIXrjN/d5OUlmFkn94",
	"zsPKe9zt+XnfbZMjC6FhyfbldFG2vZfq1B8Nhn1/eIk9PL4dDu2vd13/atDHHr4d/jy8/tcQe7g/uBpM",
	"Bv2aPXp4IASv6VmP3/XQDz+2f0D6iCJKmEKgR2r8STiT1QZ1CIrQqIZypDFhDU0JTYaG5yQizEZ17mIm",
	"g1CJeBAYIwS1HZPcANVW9NgvmgiuDU1lId+qviY97y2mgjaKPkBdu3bLeb2fTEbZYQU8XBNKmXpVaj+U",
	"2JmiKqpz4blmWvN1W8k0jolY1ilVHwjrdnCRsMwKfmsF57+ZC82VSmSn1QqDuOmYSzPgccsMli3KFiSi",
	"YYO4bI+9fTMYV40pT1m4fyiJ9FaXDXim0mSxPeMTEDGVknLWCIFROGCJlJFUzbUdAlds7d1wztn2i14Q",
	"GumT0pF1oEN5+Lmhbd9YEGEKRH0I/vCX7pXf744vbz8MhhPs4eH15N317VDHcfdqPOj2fx3827+Z3GAP",
	"jwbjD/7NjX897A+Gvgv17u3k/WA48XvdiXniDyeD8bB7ZV/+0vWvuhdXA3y/iWrOG6xX1sHWeyBR3VWJ",
	"fZ75v6RsFoHiLOcnFXyov3HpEcYZDXTiIWqegV5JSMGm51aTQy5YtkVsWeca2UdEWt522Mg5a1IP6/rn",
	"+9rqQXs3nCb1Fy43EHAWmuMJbD3klMjTvDaGsIGR6/3qbbu9ddFyoQlCmnW25eN8kceURiHKxpdNdNZs",
	"N9tHt0Cc1+YH6a6AiwWcQY6++HFnUb7lsY+yKx7j5PllcnHnkx/iURc+bpbeXvmOb1dTKbOtTbc11N/W",
	"ug91jRpXRzcyjFvv2lS8Kitqa2UNnisy0InOvOWy2UTH6bYOWlXokMSQYUB1z3+is5R7pHl9YLnnJtX3",
	"krYBQ5mLltJs3sLQ2M5DK9TDZWPVU9AKIJe12rnPrS6S7J9qe1G1BCYRXPGAO6Y3JWmkIWvS0zvb6Gq5",
	"kehk0ht56LY/qnUFRcQM1JbO2MS8LPeZrOH2XBVmo0qiq8ltZTiljTezQKCKuz3c731AI8EdbKTCYIFj",
	"BDOq5umjIQNhEOuw1sNau4O+2hXXS1QAWcdQTBgxTfHitghRVg4JF+ayeccmmup2Rz6a8ijiTxJ1B4aX",
	"spCIrFDmTFKpgAVLRALBpUSltbUQ7OGIBqCJfWGCbkKCOaBzg9DrFnh6emoS87rJxazl5srWld8bDG8G",
	"jfNmuzlXcVSivGUUK+r8zO1G2f67I78E5VmGWHmYJ8BIQnEHv2q2m68d7BuPbpGEthZnJErm5Ky1fsU2",
	"A1WXvs1VGCBSvbyTttuQ2Os9U6ekiXMoHUbmmR/iDr6iUvXKHwGUv4H6uO3eyvV57aWbuxBQHAlQqWD6",
	"mImjU+ZyLvvK6XMKphJwRxOTZ3vrJ+nvJhXm3zXlMfmmXVOQ5K3ks7ZO8rtv3+uvEikLTVvGVRWGQOg/",
	"bKsu+wZoh+6l28qy4pvYZz4vscWmOcjzdjuLVF2IdF4wSZLIdYhav0nLRAp5B3UZzNWuQYINNEyDAKSc",
	"plG0zC5OISw5ifbI1zs1SgR/jCD+/jjNbD1eo9EFCZGGOJDKrn329dbuFjUUNRzfIa3R49XX02OUF4DI",
	"FYArD7/5mqfgZ9RJYycIW1Ob9JMV6xYW0BouKDIz9LL08N6QlbrvCnrmXhARxOCpvv2zjkJ2fK/cAN0F",
	"Q3mnL4goMJX1+SBEfr/6BV8T+VPT33P5KfTuWFZHgEBPNIrQDJjWBxBhyO8379gdG1sPsfcDJ4mG9cGo",
	"cXZ+ftq5Yw101nj7CgVzIkigtUQRZzP9/EZjiYVfgiL+BCIgElAEmqEjLlBIZ1TpkW67iLNoWRkpPQey",
	"0jOt8/kymQMzd1MDFlr5hUw7dONjku2fm26AmfnKtHCqv/YzxlpINBBwwcPlX4+G1uPXv5ldVWD47O9a",
	"eNtdgLspR7IEyt/w95+Cv6/bP309DXqcTSMaKNRAfUgivjQ3eSaipS4ezVcgrq+IXF/xn5gjHMiXUbs2",
	"Say8reQ26x7s4LipYNJeg69161yFLfOyej2hXIJ6X/Ta/iYG9j5rfVSpl6sIqERZW27ddq6N15tD8Klk",
	"Nydxt802Puc1RotA1RTyffNck/HsFuGAXGwn7cjFdSYphrQ2/22ihgS/3nVrajdTh5Tf0CrT4PVXRSt3",
	"MJpC2VuRfyIaOV/fi0be3mp6R7CgxyXy+3Vo87fGS/trs5WiWvwWhd+i8IgovAR1ACFwX0PUF3c//7ir",
	"t5Z38VomUJz8LbdkgU6vKI9VWZQ8Wer2tuehiE4hWAYR2FamKQRrZZX2trpf/TcAAP//7XBetFQ4AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
