// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb7XPiOJP/V1S+/ZDcGsjbzLMPX+4IsBnXZgiVkL3bmuRSit2AnrEljyQnYbP5369a",
	"kl/AhkBuZmqvar4ZW2q1Wt2/fhPPXiiSVHDgWnndZy+lkiagQZpffcE1ZRxkEI2pnuOrCFQoWaqZ4F7X",
	"u+bsSwaERcA1mzKQZCok0XMgYT7V8z14okkag9f1kkWLzxh/alU/M6SUIn3f4zTBccXnOxZ5vifhS8Yk",
	"RF5Xywx8T4VzSKjlV2uQSOB/PtHWnwetf97uuYfW7fOB//7wJX+//x8/eb6nFykuoLRkfOa9vLzk1JY3",
	"XN9q8YlIUCKTIRAJqQSFW+czQsstE8aVpjwEz/dSKVKQmoGhH0qgGu40w12urjBhCShNk5Q8zoEvS5E8",
	"UkXsbBTIVMiEaq/rRVRDy5BDKdHogseLXEorW/U90HRWX/YipXiGDyAVE3z1LEWqWcKUZiEyE2ZSAg8X",
	"ZK83HLcO353st8kAJHuAiEylSAzTGY9AxgsUym/ZPUgOGlQpNbdQexuOWfQmnasewCvKl9Cnc+AzVO73",
	"x76XMJ7/PPR3165XN5Q2mtFlLhv8XNnZEvsF16rTuJNX11YgH1hoFI/G8cXU63569n6SMPW63r91Shzo",
	"OIPoXNkJAZ8K7+V2dQWkmEKI5DYRKezmCgfjJE11prbnoiRgJzZykjVpytVCaUhaVCk24xARliSZpvcx",
	"quiqDlmFPvnlDQp9HQy2UuYsjf4Pxh9TpYkl8VYEeKki6Sd7erfFKHH/Lwi153tPLQppK99eBWUVzqqo",
	"4XMVpl+QVBpnksZLyur5nmJ8lsVUVt+XUPz5F1XqccspaSuV4oFFINtRmLSZ6JQTcRuFTvTTzGhSFDEU",
	"JI3HFby1QliB8fF1eXKh4EpLytD5rUJ1Qp/qp/SRPrEkSwiNY/EIEUFqoZCA0xPG8ZsBDrc1xjXMkGXz",
	"tYGcnUJmGZWUa9iB4spZInkDZvUDrYpryB9+p3I3iQ35A5OCJ8A1eaCSGQOKYMq4IVATnHXhz9tQMUMb",
	"LOWBxtm2NOzY13TdrWQHbxRRkNAZ7KhTpd/ByQQNi01ZSBvlI2EK6EShKcZArNdALvqBo1WMbt/wX43N",
	"d8mny+FZcDW5/KNzezkcX1wFk4vLPz51J72zv/5zEJwNrya3N3zJd3zJ6AKtKFnQNO0+HLaPXpVYyeZG",
	"cZ0zpesbGdMZ44hUJGZKEzFt8M11k6uARvfZYxoStbV3QaYcl1RKusDfHJ70XUpncKfFZ2iwvwm+NuGD",
	"BC0ZPCDEI/TiTIIzkXUJKosNQtQltl4wHyERcrGbItk5XxGfEkvwkek5+jxN9qA9a/vkxjs6O73x8OEE",
	"H/a95WAHI5qf9z6e/nV2+tfkdP+nJiPdFtHW83CY83D0Nh7ehoEfQdOIarohDEvcEKMaeZCwxpxjeg+x",
	"Wn/Oz3XJrRh9prRIyGdYtAw8kZQyqWxQS2czk1vwiExZrMFQaNhcM+YW+8HPy2Hl7mFvyz39+8Z8yrKi",
	"UtoEb5XgqRiF4Y6EQuUVecSfZaazW0hj5LDx9EegH4X8vJtdukloj1M2y2SzJrC0AQhFRIIxoVEkQamt",
	"MgQhbSq+zseYAUQLAk+pUOjVdkPKsZC6jpYbscxMeaNLRHY3hQtlDJm6VVYlKDXhWXJvXQeLlmsLiUU8",
	"r/v+3bvjd69FYQ9MsXsWM72oL/RBPBI9Z8pyzJSTb4SiRiDOEpCqfcNbhAsOXTJ2w7jQxVCRacPhcvie",
	"ShGCUjgVeZGcxl0yLKnj6LlAPylJGGdKgyTcqtwNJzleDkT4GSRppX41C+nb8cGYuGxtH5eBp3yZS6Dh",
	"3ARKJp2pMohLdtx6lXUuUuBXczbV5FJkGpZWC/gM9bhzLmh0SmN043Lfxhochf7JQ9mYmo5lwEQh7vG2",
	"GpFUBmw26RX9WDrDjZY+tlJ/s97a6a/YPJWzBmPtyVmGUarKTxe4lotUMK6r5lqz/dUAJhRJQnnUFAnn",
	"9Ih4AClZBDsRBv6wXXitdoYXl2LsBjC5p1K7J3PoG5Md4qbQZoxb7QWzS4x0ilBuq1ku8qspcpp5Ba2N",
	"mnvlyirrVHMpv7CBFeNppsmUQRzZ0MF40JW6ZN1j5bnOVvuymZGRRxlBbSkRN8EE5YUD3mpu7rBfDPO5",
	"RW/n6dx4O9WUE+7mzFW6t9eyi9SOIzmRVn4AxFArC0Uh1TQWM7JHwxBSDZFvvAMNMRPKUsH3m4I3WVX+",
	"rTZWmktZ1ruzdGs1MPuV4NeleleSKU3ugdyUCGtj8BzJS7W5fbWSVGWhoh++07DqHjdrflEbXI2RpURY",
	"srVDTMrW13sd++PhaBCMzjzfu7wejezTr73gfDjwfO969Nvo4r9Gnu8NhufDyXDQsEffG0opGjoBl7/2",
	"yT9+OfgHwSOKGeWaAI5E/EkFV/WyfwSasrgh5MgSylsYEhoPDU9pTLm16kLFjAdhiojQFd8bKyaFALYu",
	"l2OAY7heIlyUFTPJWmUJoKmavOaoPkwm4/ycQhEtEWVcH1cqD5XATDMdN2nvHIOs+bKYVJYkVC6amGq2",
	"AXOO1gIcR7mSBKPfe+fB4K53eXb9cTiaeL43upjc/XpxPUI16Z1fDnuDP+6G/x1cTa483xsPLz8GV1fB",
	"xehuMBwFTpd615MPw9Ek6Pcm5k0wmgwvR71z+/H3XnDeOz0fooptK94V+3J2ZYXUZEAfgMZNjQX7Pj8O",
	"xfgsBi144Slrmtrcn+hTLjgLEQKpnufmVyFSxnVzy8k27Yh1ClTluYH2DgdfJMAr6LdEdbv6c7GvtUe4",
	"Rf2/ufR/BaHgkTme0EbmjonC4aAwpM2HC76P3x8crF20mvLYdtt6z1Ascp+xOMrbc0siOmwftA92Tsad",
	"1hYH6Vq85QJOIDu3INxZVPsN9lXebDBKXjSLy+5DcYg7tR7cLNxetSO2qbyRy9YCf0MQarOuu6aSgcvo",
	"WnmGtFw/qDd1XXrVSGv4VKNB9hD/qwmcsY59b/taRKE55vOWCYKb1Fx9WGfA1eilAttF0ot4LSJL1Peq",
	"m2oOWmrAWeVq4z7XHmX6+lRbvWj0e6kUWoTCxQZTmsUILZM+7mylDuJGkr1Jf+yT68G48cg0lTPQa2op",
	"E/OxWpmwgnuluZSPqpCuO6EXE4VYuzALhLrsBnmD/kcylsKZdyaNzWqdqm6nM2N6nt23Q5F0ojBB88Nh",
	"nc3GWa+j4hI14ERdTyinpoxa9hcI49WyhjNH1b7hEwyMeuOATEUci0dFekMTzvCIyjy1Elwxpc09CBpK",
	"oRSprI1EPN+LWQgYCpYi6KU0nAM5Mki6LIHHx8c2NZ/bQs46bq7qnAf94ehq2DpqH7TnOokrkVIVbcrM",
	"MFe7cb7/3jioQG6O5C++J1LgNGVe1ztuH7RPHDwbje7QlHUeDmmczulhZ7kpMwPd5GZN8wQIrbd7lM1P",
	"U9sQMpFtljqFQjMy74LI63rnTOl+tW1cvYv0aV2nw1UGbZvGlZC1IBJ0JjkeM3Vhj2nn5LeNvmRgAkh3",
	"NAl9sn0ixf40Lqu4X1TY5LuDhji2KD4eHqAz3tyvbW4+MR6ZRN41noyjxx+2uJPfbNnAe6W/VWW8hn21",
	"GtVw3Do8PnJ9Bcw90DvgARXZK7nPtElgF6AJw1ggAa4h2l/DiiX1NjaEjEx346swYojd3S82smKukdiE",
	"zaj20cFBjl3Abbk7TWNXZen8S9kYqqS3VaZu2qMGG1f8QxaGoNQ0i+NF3nyEqGI2aKMnGzlKpbiPIfl5",
	"N85sTtvA0SmNCII+KG3XPvx+a/cyPcfY3FW0Ct9j+Dj+fnyMQSbM6l4EnFkO3n3PUwjyoA+9CZqlG+h7",
	"edZrgZIsIaWmMxMYV17emvCtqTffN701QgmHx+YSyjIu2/H9ahFxEzAX1bIwZsB1XiuDiASD+k29Ngmm",
	"xrKdx478G55nQCDJI4tjMgOO/AChnASD9g2/4ZdWQ2yNfS9FR4c4cnS0373hLXLYen9MwjmVNEQuSSz4",
	"DN9fIbpah0RJLB5BhlQBiQFzCyIkidiMaRzptksEjxe1kcp3bkf5pvw8X6Rz4Ka/M+SRpV/StENXLmSs",
	"vwi7AmXm/mupVF/3umIjJBoIOBXR4uujodX45du8LzUYPvxWC6+rp7tuM1EVUP6Bv38X/D05+Of346Av",
	"+DRmoSYtMoA0FgvTDTMWrWjiblLQWAKNFgSemNLqb+kjHMhXUbvRSbz4a8P9vO6xIerPJFe2lbxUZ3T1",
	"wfy+8apDOQP9oawSfqMI7ENetKmHXi5HYorkBcVl2bkCZH8O4eeK3BzFzTJbuRJrhBaDbihtDMx7TE/y",
	"Sv8WvthO2uCLm0RSDums/qGjIQg+2dR5tJtpQsofaJVzcPJd0codDIZQU5Hxv2fE6nT9VTTyX60vbDAW",
	"cr8gwaAJbb6pvRx872ilzBZ/WOEPK9zBCs9Ab2OCKdVh01/9zF9PMAczYc9SPbW0wUzhhwTkDFqGEFGQ",
	"UFQTVbNMS/FrG+c26UuFv5+/aSrz3cHB/UHoRyrzA5b+v8CSA5bXUxV316m57PTbL5v6IEXHpWNQwtFf",
	"c/MgxMCfFFilymJMnlT46yPkmE0hXIQx2LaTKVE10qrs7eX25X8DAAD//2R70QWIPQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
